version: '2'
services:
  node:
    build: 
      context: node
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "$PWD/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    links:
      - grafana
      - node
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SERVER_ROOT: "http://localhost:3000"
      GF_SECURITY_ADMIN_PASSWORD: "grafana"
    ports:
      - 3000:3000
